#import "../dcthesis.typ": short

= Sample Decent Chapter Title

Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around!

#short[Shorter Title]
== Section with an Unnecessarily Long Title

Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around!

=== Example of a subsection

Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around!

==== Subsubsections, the final formatted heading
//
Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around!

== A Second Section

Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around! Every good story begins with a twist. Let's test it out and see how it goes. Beginning to ending, just spin around!
